// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterMethodCodec;
@class FlutterError;
@class FlutterStandardTypedData;

@class FLTMbxEdgeInsets;

NS_ASSUME_NONNULL_BEGIN

/// The distance on each side between rectangles, when one is contained into other.
///
/// All fields' values are in `logical pixel` units.
@interface FLTMbxEdgeInsets : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithTop:(NSNumber *)top
    left:(NSNumber *)left
    bottom:(NSNumber *)bottom
    right:(NSNumber *)right;
/// Padding from the top.
@property(nonatomic, strong) NSNumber * top;
/// Padding from the left.
@property(nonatomic, strong) NSNumber * left;
/// Padding from the bottom.
@property(nonatomic, strong) NSNumber * bottom;
/// Padding from the right.
@property(nonatomic, strong) NSNumber * right;
@end

NS_ASSUME_NONNULL_END