// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterMethodCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

/// The codec used by FLT_MapInterface.
NSObject<FlutterMethodCodec> *FLT_MapInterfaceGetCodec(void);#


NS_ASSUME_NONNULL_END