// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterMethodCodec;
@class FlutterError;
@class FlutterStandardTypedData;

@class FLTScreenCoordinate;

NS_ASSUME_NONNULL_BEGIN

/// Describes the coordinate on the screen, measured from top to bottom and from left to right.
/// Note: the `map` uses screen coordinate units measured in `logical pixels`.
@interface FLTScreenCoordinate : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithX:(NSNumber *)x
    y:(NSNumber *)y;
/// A value representing the x position of this coordinate.
@property(nonatomic, strong) NSNumber * x;
/// A value representing the y position of this coordinate.
@property(nonatomic, strong) NSNumber * y;
@end

NS_ASSUME_NONNULL_END
