// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterMethodCodec;
@class FlutterError;
@class FlutterStandardTypedData;

@class FLTTransitionOptions;

NS_ASSUME_NONNULL_BEGIN

/// The `transition options` controls timing for the interpolation between a transitionable style
/// property's previous value and new value. These can be used to define the style default property
/// transition behavior. Also, any transitionable style property may also have its own `-transition`
/// property that defines specific transition timing for that specific layer property, overriding
/// the global transition values.
@interface FLTTransitionOptions : NSObject
+ (instancetype)makeWithDuration:(nullable NSNumber *)duration
    delay:(nullable NSNumber *)delay
    enablePlacementTransitions:(nullable NSNumber *)enablePlacementTransitions;
/// Time allotted for transitions to complete. Units in milliseconds. Defaults to `300.0`.
@property(nonatomic, strong, nullable) NSNumber * duration;
/// Length of time before a transition begins. Units in milliseconds. Defaults to `0.0`.
@property(nonatomic, strong, nullable) NSNumber * delay;
/// Whether the fade in/out symbol placement transition is enabled. Defaults to `true`.
@property(nonatomic, strong, nullable) NSNumber * enablePlacementTransitions;
@end